In [7]:
from numpy import array

data = array([[0, 1,  2,  3],
              [4, 5,  6,  7],
              [8, 9, 10, 11],
              [1, 2,  3,  4]])

In [8]:
from Bio.Cluster import distancematrix

distances = distancematrix(data, dist="e")
distances

[array([], dtype=float64),
 array([16.]),
 array([64., 16.]),
 array([ 1.,  9., 49.])]

In [16]:
from Bio.Cluster import clustercentroids
cdata, cmask = clustercentroids(data)
cdata

array([[3.25, 4.25, 5.25, 6.25]])

In [21]:
from Bio.Cluster import clusterdistance
distance = clusterdistance(data)
distance

0.0

In [19]:
from Bio.Cluster import kcluster
clusterid, error, nfound = kcluster(data)
clusterid

array([0, 1, 1, 0], dtype=int32)

In [22]:
from Bio.Cluster import treecluster
tree = treecluster(data)
tree

In [24]:
from Bio.Cluster import somcluster # self-organising maps
clusterid, celldata = somcluster(data)
clusterid

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0]], dtype=int32)

In [27]:
from Bio.Cluster import pca
columnmean, coordinates, components, eigenvalues = pca(data)
columnmean

array([3.25, 4.25, 5.25, 6.25])